name: Build app and deploy to tengxunyun
on:
  #监听push操作
  push:
    branches: [main]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/gradle/caches
        key: runner.os -build-env.cache-name- hashFiles('**/package-lock.json')
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.13.1'
        cache: 'yarn'
    - name: yarn vetsion
      run: yarn -v
    - name: Install yarn dependencies
      run: yarn
    - name: Run build task
      run: yarn run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: build # 这是要复制到云静态服务器的文件夹名称
        #   SOURCE: ${{ secrets.SOURCE }} # 这是要复制到云静态服务器的文件夹名称
          REMOTE_HOST: ${{ secrets.YOU_HOST }} # 你的阿公网地址
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # 登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: ${{ secrets.OUTPUTPATH }} # 打包后的 dist 文件夹将放在 /root/node-server