name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches: [main]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.13.1'
    - name: Install npm dependencies
      run: npm -v
    # - name: Run build task
    #   run: npm run build:dev
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: AJAX # 这是要复制到阿里云静态服务器的文件夹名称
          REMOTE_HOST: '1.15.110.27' # 你的阿里云公网地址
          REMOTE_USER: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: /root/node-server # 打包后的 dist 文件夹将放在 /root/node-server