name: vue/cli # 显示名字

on:
  push:
    branches: [main] # main分支push就执行该工作流

jobs:
  build:
    runs-on: ubuntu-latest # 在最新的ubuntu机器上

    steps:
      - uses: actions/checkout@v3 # git 克隆到当前机器上
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x # 使用16的node版本
          cache: 'yarn'
      # - run: yarn global add @vue/cli # 全局安装@vue/cli
      - run: yarn -v # 查看版本